### ISSUE TITLE
:GV outputs Unkown function: FugitiveShellCommand

### ISSUE THREAD

**Issue by Nishant-Pall** [junegunn/gv.vim#101]
I installed gv.vim, and if I try to type in the command :GV or any other command, I get something like 
`Vim(call):E117: Unknown function: FugitiveShellCommand `
in the output, it  doesn't open a buffer at all.
Is it because of existing plugins causing the error, I do have vim-fugitive installed.

I'm on Ubuntu 20.04 LTS, with neovim 0.5.0

**Comment by justinmk** [comment]
your fugitive is out of date

**Comment by Nishant-Pall** [comment]
Got it working, had to give an update that's all. Thank you
