### ISSUE TITLE
:w creates a file named `p --graph`

### ISSUE THREAD

**Issue by bart9h** [junegunn/gv.vim#108]
Just a minor issue: if you give the `:w<CR>` command in a GV window, it writes a file named `p --graph`.

Maybe set `buftype=nofile` on the GV buffer?

**Comment by junegunn** [comment]
https://github.com/junegunn/gv.vim/blob/386d770e916dd680d1d622e715b9eb3a77f21bd1/plugin/gv.vim#L175-L177

We already do, and I can't reproduce the problem.

**Comment by bart9h** [comment]
Now I also tried unsuccessfully to reproduce the problem.

I have no idea how this happened before (and it was certainly more than once).

Since it seems that GV is not a fault, I'll close this issue. Sorry for taking your time.
