### ISSUE TITLE
Operations on commits

### ISSUE THREAD

**Issue by CaptainQuirk** [junegunn/gv.vim#11]
Hi,

Could you implement other actions on commit items such as

- reset --hard (with confirmation)
- reset --soft
- revert
- format-patch

**Comment by junegunn** [comment]
Thanks for the suggestion but this is beyond the scope of this plugin. You can however consider using fugitive to take arbitrary action on the commit. When you press `.` on the commit buffer, fugitive will open Vim command-line with the commit hash at the end, so for example,
- Press `.`
- Type `Git format-patch`
- Enter
You can also define key mappings for such things with `autocmd FileType git`.
