### ISSUE TITLE
Feature request: retrieve the commit log for a specific line in a file

### ISSUE THREAD

**Issue by mroavi** [junegunn/gv.vim#119]
While I love the mapping feature that allows you to view the commit log for a given file, having the option to log the commits that touched a **specific line** of a given file would be super convenient. It turns out that Git has a mechanism for this, as explained here: https://stackoverflow.com/q/8435343/1706778.

Would you be interested in adding this functionality to your package?

**Comment by junegunn** [comment]
Visual-select the lines and run `:GV` as usual.

https://github.com/junegunn/gv.vim?tab=readme-ov-file#commands

**Comment by mroavi** [comment]
Didn't think about doing that. Thanks!
