### ISSUE TITLE
GV! -> fatal: bad flag '--color=never' used after filename

### ISSUE THREAD

**Issue by jonbri** [junegunn/gv.vim#12]
**To rep:**
* clone gv.vim and cd gv.vim 
* open vim
* :e plugin/gv.vim
* :GV!
* This opens a scratch buffer with one line of text: *fatal: bad flag '--color=never' used after filename*

Using the "GV" command without the bang seems to work just fine (brings up the tree view)

**System details:**
gv.vim at sha: 84b61f0
Lubuntu 15.04
lxterminal
git version 2.1.4
Fugitive is up-to-date (sha: fd36aa9)
Both Fugitive and gv.vim are installed with Pathogen

**Comment by jonbri** [comment]
Also, the "GV" command seems to work just fine.

**Comment by junegunn** [comment]
That's strange. Can you add `echom git_log_cmd` between line [197 and 198](https://github.com/junegunn/gv.vim/blob/84b61f0af37d710701a99564c08308352a34241c/plugin/gv.vim#L197-L198) and check the output of it with `:messages` command?

**Comment by jonbri** [comment]
The echom statement prints:

git --git-dir=/home/jonbri/.vim/bundle/gv.vim/.git log --follow plugin/gv.vim '--color=never' '--date=
short' '--format=%cd %h%d %s (%an)'

**Comment by gchaincl** [comment]
I'm havinf `fatal: bad flag '--color=never' used after filename` when running `GV!` too

**Comment by junegunn** [comment]
Should be fixed in e87d864231306e68da424c53e0af47e733ba6ffa.
Thanks for the report!

**Comment by gchaincl** [comment]
Thank you very much, works perfectly @junegunn !

**Comment by jonbri** [comment]
Works great, thanks!
