### ISSUE TITLE
add format option

### ISSUE THREAD

**Issue by olshevskiy87** [junegunn/gv.vim#2]
hi! thank you for handy tool)
it would be nice to be able to change some format option. for example, i would like to add the author name, i.e. %an placeholder.

**Comment by junegunn** [comment]
Added `%an` to the line.
Custom formatting will make the code much more complicated than I'd like it to be, and I really want this plugin to be "config-free" :)

**Comment by olshevskiy87** [comment]
> Added %an to the line.

thank you very much! )

**Comment by CaptainQuirk** [comment]
Hi there !

Thanks for the work !

Can you explain why a custom formatting would make the code more complicated ? I don't do vimL for now, but cannot the format be retrieved from a global option in the s:list function ?

**Comment by junegunn** [comment]
@CaptainQuirk Syntax highlighting should be updated to handle arbitrary layouts. And honestly I don't have time to implement the options that I don't need. Feel free to fork the repo if you need different formatting.
