### ISSUE TITLE
Unknown function: systemlist

### ISSUE THREAD

**Issue by AssailantLF** [junegunn/gv.vim#21]
When I run `:GV`, I receive the following error, and it's unable to continue:

    Error detected while processing function <SNR>38_gv:
    line   13:
    E117: Unknown function: systemlist
    E15: Invalid expression: systemlist('git rev-parse --show-toplevel')[0]

I'm running on Windows, and fugitive works as well as a few of your other plugins that I use. Any ideas?

**Comment by justinmk** [comment]
@AssailantLF It means you're running an old version of Vim. README implies that back-compat is not a goal of GV.vim.

**Comment by AssailantLF** [comment]
Oh wow, you're right. Reinstalling Vim from the _latest version_ link for MS-DOS on vim.org worked. I honestly hadn't noticed that link before and always had used the regular _self-installing executable_.

Thanks, this mod is really great.
