### ISSUE TITLE
File mode?

### ISSUE THREAD

**Issue by luisdavim** [junegunn/gv.vim#22]
Hi, gitv has a file mode where we can compare, side by side two revisions of the same file, is this possible with gv.vim? If not, are you planing to implement anything like it?

Thanks.

**Comment by justinmk** [comment]
You can already do that with fugitive.vim.

**Comment by luisdavim** [comment]
Yes, but gitv makes it easy to compare revisions whilst browsing through the revisions.

**Comment by junegunn** [comment]
You can list the commits for the current file only with `:GV!`, but no, there's no such "file mode".

`:Glog` from fugitive gives a similar view, so maybe we can think of a solution based on it.

Related? https://github.com/tpope/vim-fugitive/issues/329

**Comment by luisdavim** [comment]
That sounds like what I'm looking for.

Thanks.

**Comment by junegunn** [comment]
Also remembered that I liked that bit from gitv. I'll let you know if I come up with something.

**Comment by luisdavim** [comment]
Awesome, thanks.

**Comment by junegunn** [comment]
So here is what I came up with:

```vim
function! s:gl(buf)
  if !exists(':Gllog')
    return
  endif
  tab split
  silent! Gllog
  call setloclist(0, insert(getloclist(0), {'bufnr': a:buf}, 0))
  b #
  lopen
  xnoremap <buffer> D :call <sid>gld()<cr>
  nnoremap <buffer> o <cr><c-w><c-w>
  nnoremap <buffer> q :tabclose<cr>
  call matchadd('Conceal', '^fugitive:///.\{-}\.git//')
  call matchadd('Conceal', '^fugitive:///.\{-}\.git//\x\{7}\zs.\{-}||')
  setlocal concealcursor=nv conceallevel=3 nowrap
endfunction

function! s:gld() range
  let [to, from] = map([a:firstline, a:lastline], 'split(getline(v:val), "|")[0]')
  execute 'tabedit' to
  execute 'vsplit' from
  windo diffthis
endfunction

command! GL call s:gl(bufnr(''))
```

`:GL` will open a new tab, pressing <kbd>D</kbd> over a visual range of revisions will show the split diff between the top and the bottom.

**Comment by luisdavim** [comment]
Thanks!  Did you add this to the code?

**Comment by junegunn** [comment]
Haven't decided if I should add this to gv.vim or not. I currently have it on my vimrc.

**Comment by luisdavim** [comment]
It is an extra feature that adds functionality to the plugin why would you not?
Meanwhile I'll keep it in my vimrc.

Thanks.

**Comment by junegunn** [comment]
Because in principle it's an extension of fugitive rather than gv.

**Comment by luisdavim** [comment]
Isn't that what GV is?
