### ISSUE TITLE
Git command not defined in GV buffer

### ISSUE THREAD

**Issue by SolaWing** [junegunn/gv.vim#24]
<img width="408" alt="2016-06-17 11 20 15" src="https://cloud.githubusercontent.com/assets/3897953/16139779/84c9d6c8-347d-11e6-9a4f-573198565eb2.png">
as title says, this make 

> . to start command-line with :Git [CURSOR] SHA à la fugitive

useless

**Comment by justinmk** [comment]
A simple `call fugitive#detect(@#)` should be all that is needed.

**Comment by junegunn** [comment]
@SolaWing Thanks for the report. @justinmk Nice, thanks.

**Comment by eloytoro** [comment]
I can't get this to work on neovim, is it supported?

**Comment by justinmk** [comment]
@eloytoro Works for me in neovim.

**Comment by eloytoro** [comment]
It seems I'm having a fugitive relative issue
https://github.com/tpope/vim-fugitive/pull/785#issuecomment-228630162
Thanks for testing @justinmk, but how this works for anyone bewilders me

**Comment by justinmk** [comment]
> how this works for anyone bewilders me

What do you mean by "this"? https://github.com/tpope/vim-fugitive/pull/785 is a different issue than the problem addressed by this change.
