### ISSUE TITLE
Show commit body in the horizontal split

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/gv.vim#25]
Hey, I could you add a setting so I can open commit's body in a horizontal split?

**Comment by junegunn** [comment]
Isn't that what <kbd>Enter</kbd> (or <kbd>o</kbd>) does?

**Comment by yevhen-m** [comment]
No, enter and o split my window vertically, but it's convenient only
starting from some width of the window. So I want to be able to open commit
body in a horizontally split window.

**Comment by junegunn** [comment]
Oh, I see. I was confused about horizontal vs. vertical (for one thing tmux uses the terms in the opposite ways). Anyway there is no such option, but you can change the layout with <kbd>CTRL</kbd><kbd>w</kbd><kbd>K</kbd>. I think it's enough for now.

**Comment by kiryph** [comment]
If anyone wants to change this permanently in his own repo, you can modify the code as following:

```diff
diff --git a/plugin/gv.vim b/plugin/gv.vim
index a16fae4..f7963d8 100644
--- a/plugin/gv.vim
+++ b/plugin/gv.vim
@@ -88,7 +88,7 @@ function! s:split(tab)
     $wincmd w
     enew
   else
-    vertical botright new
+    botright new
   endif
   let w:gv = 1
 endfunction
```
