### ISSUE TITLE
Cosmetic improvement

### ISSUE THREAD

**Issue by luisdavim** [junegunn/gv.vim#26]
Hi,

I know this is not really important and I understand if you ignore my erquest.
The git log graph from https://github.com/gregsexton/gitv looks a little bit better in my opinion, specially because it does not have trailing spaces in the lines without text and the paths are colored.

Could you change the git log parameters to address this?
Thanks,
Luis

**Comment by junegunn** [comment]
GV simply reads the output of `git log --graph ...` command, and the trailing spaces are from that. I'm not aware of a `git log` option that removes them. Anyhow, it's really trivial for GV to strip them out after filling the buffer with the output.

```diff
diff --git a/plugin/gv.vim b/plugin/gv.vim
index 93b8d88..0c74966 100644
--- a/plugin/gv.vim
+++ b/plugin/gv.vim
@@ -219,6 +219,8 @@ endfunction
 function! s:fill(cmd)
   setlocal modifiable
   silent execute 'read' escape('!'.a:cmd, '%')
+  %s/ *$//
+  nohlsearch
   normal! gg"_dd
   setlocal nomodifiable
 endfunction
```

However, it adds a noticeable delay when there are many number of commits. For example, for a repo with 10K commits:

```
# No post-processing
time vim +GV +qa

real    0m0.390s
user    0m0.267s
sys     0m0.081s

# Stripping out trailing spaces
time vim +GV +qa

real    0m0.724s
user    0m0.367s
sys     0m0.316s
```

This makes me hesitate. Because my Vim configuration does not highlight trailing whitespaces on GV buffer, and snappy execution is much more important to me.

```vim
  " http://vim.wikia.com/wiki/Highlight_unwanted_spaces
  au BufNewFile,BufRead,InsertLeave * silent! match ExtraWhitespace /\s\+$/
  au InsertEnter * silent! match ExtraWhitespace /\s\+\%#\@<!$/
```

Highlighting URLs is doable, but I don't think it's common to include URLs in commit message? Any example?

**Comment by luisdavim** [comment]
Hi,

Thanks for the reply if it affects performance I guess it's not that important :)
The other part was not about highlighting, it was about coloring the paths in the graph, different colors for each branch.

**Comment by junegunn** [comment]
Oh I see, the graph. I thought about that before. Here's the thing; we have a few options, but none of which is good enough:

1. Keep the ANSI color codes from `git log --graph` with `--color=always`. Using Vimscript, extract the raw ANSI codes in the text and map each colored section to a Vim syntax highlight group. You can imagine how much it will slow down the GV when simple `%s/ *$//` makes it about 2x slower.

2. Parse the graph in Vimscript. Commit graphs can be extremely complex (see the below image), I wouldn't even dare to try to parse the textual graph representation in Vimscript.

![linux](https://cloud.githubusercontent.com/assets/700826/16252478/87d84288-3869-11e6-819a-ca502d7de338.png)

3. Coloring solely based on the level of indentation. This is the only practical option we have, but obviously it will color the edges incorrectly. I'm not perfectly sure, but gitv seems to have taken this route and gives incorrect, misleading colors. See below:

![gitv](https://cloud.githubusercontent.com/assets/700826/16252564/682e9bfc-386a-11e6-8162-6d44246cb325.png)

**Comment by luisdavim** [comment]
Yes, the last option seams to be the best, I didn't noticed that issue before with the edges but you are right.

**Comment by junegunn** [comment]
We don't have a good option, so colored graph is a no-go, at least for now.

As for the trailing whitespaces, If you don't mind the extra delay, you can strip them by yourself.

```vim
autocmd! FileType GV set ma! | %s/ *$// | nohl | 1 | set ma!
```
