### ISSUE TITLE
New mapping request in tree type window

### ISSUE THREAD

**Issue by vbauerster** [junegunn/gv.vim#29]
Dear Junegunn!

Please consider the situation when one browsing a git tree. It is easy to drill down through the directories, but it’s not obvious how one could go up a level to the parent directory. Running the following command will open the parent tree:

`:edit %:h`

This problem first addressed by Drew Neil, in his [vimcast](http://vimcasts.org/episodes/fugitive-vim-browsing-the-git-object-database/) blog. Drew proposed the following solution:
```vim
autocmd User fugitive 
  \ if fugitive#buffer().type() =~# '^\%(tree\|blob\)$' |
  \   nnoremap <buffer> .. :edit %:h<CR> |
  \ endif
```
However, instead of copy pasting this, I'd like this snippet to be integrated into gv.vim plugin.
The plugin already maps <kbd>.</kbd>, so good mapping candidate for this would be just <kbd>u</kbd> same as in NERDTree plugin. I think it is pretty obvious to press <kbd>u</kbd>, while in tree buffer, to go one level up.

**Comment by justinmk** [comment]
Why not make this request at fugitive? It's not appropriate for any plugin but fugitive. I even considered adding it to [dirvish.vim](https://github.com/justinmk/vim-dirvish) but decided against it.

**Comment by vbauerster** [comment]
@justinmk ok I'll try make request at fugitive. Thanks for hint.

**Comment by vbauerster** [comment]
I've posted the request at fugitive.
https://github.com/tpope/vim-fugitive/issues/828

**Comment by vbauerster** [comment]
The issue may be closed, as fugitive provides <kid>-</kid> key for aforementioned behavior.
