### ISSUE TITLE
Remain highlighted after selecting comment(s)

### ISSUE THREAD

**Issue by Ephemera** [junegunn/gv.vim#3]
<img width="296" alt="screen shot 2016-01-15 at 11 27 53 am" src="https://cloud.githubusercontent.com/assets/1617580/12344080/d687b8e2-bb7c-11e5-991e-0b2d6f679b2a.png">

But It is disappeared after moving cursor to split view

**Comment by junegunn** [comment]
> disappeared after moving cursor to split view

vim-oblique? Pressing <kbd>n</kbd> will resurrect the highlighting.

**Comment by Ephemera** [comment]
I think because of vim-signature. I will find more information.
And  <kbd>n</kbd> does not work. It just seems like search match, but it doesn't.

**Comment by moon-musick** [comment]
Experiencing the same problem, and disabling [vim-signature](https://github.com/kshenoy/vim-signature) helps indeed.

Opening a split or tab view with commit contents highlights spaces. They stay highlighted until the focus is moved to the new view (i.e. manually in case of a split, and automatically when using `O` - the highlights disappear in a new tab in a fraction of a second after switching to it, not really an issue in that case, but the behaviour is apparently consistent).

**Comment by junegunn** [comment]
Pretty sure that this is an issue of signature as it's reproducible outside the context of gv.vim.

```vim
function! s:xxx()
  split fugitive:///Users/jg/.vim/plugged/gv.vim/.git//e87d864
endfunction
nnoremap <silent> xxx :call <sid>xxx()<cr>
normal xxx
```

I have no idea what's going on. Consider reporting the issue to the author of vim-signature.
