### ISSUE TITLE
Default diffs to unfolded

### ISSUE THREAD

**Issue by jonahx** [junegunn/gv.vim#30]
Amazing plugin.  Thanks for making it.

When I open commits with `<cr>`, the diff info in the commit details pane on the right is folded.  How can I make it unfolded by default?

**Comment by mhinz** [comment]
You could try:

```vim
autocmd FileType GV set foldlevel=1
```

**Comment by jonahx** [comment]
Perfect, thanks!  For posterity I actually had to do:

```
autocmd FileType git set foldlevel=1
```
