### ISSUE TITLE
Default tab place

### ISSUE THREAD

**Issue by ipod825** [junegunn/gv.vim#31]
GV opens a new tab on the left of the current tab by default [47](https://github.com/junegunn/gv.vim/blob/master/plugin/gv.vim#L47)
It would be nice to add an option such that user can specify the new tab is created on the right of the current tab.

**Comment by junegunn** [comment]
Hi, opening GV tab on the left has the benefit of returning to the original tab when it's closed even if you have multiple tabs (`vim +tabnew +tabnew +tabp +GV`). So I don't think we need an option for that. If you really want to change that, please consider forking the repository. GV currently doesn't have any options and I'd like to keep it that way. Thanks.
