### ISSUE TITLE
Error when there is some spaces in the path

### ISSUE THREAD

**Issue by tdehaeze** [junegunn/gv.vim#35]
Hi,
Love this git commit browser, however I have a problem when there is some spaces in the file path :
```
Error detected while processing function <SNR>28_open:
line   11:
E172: Only one file name allowed: e fugitive:///Users/... containing spaces .../.git//609db6f
```
Could you fix it ? Or is this coming from me ?

Thanks

**Comment by junegunn** [comment]
Should be fixed, thanks.

**Comment by tdehaeze** [comment]
Indeed, it's fixed.
Thank you very much
