### ISSUE TITLE
Conflicting '?' error with plug 'on' configuration

### ISSUE THREAD

**Issue by mad-raz** [junegunn/gv.vim#37]
adding any of the following configuration to my vimrc
```
Plug 'junegunn/gv.vim', { 'on': ['GV?', 'GV!'] }
Plug 'junegunn/gv.vim', { 'on': 'GV?' }
```
causes vim to fail to start with the following error
```
Error detected while processing function plug#end:
line   61:
E182: Invalid command name
Press ENTER or type command to continue
```
using it without `?` works fine

**Comment by junegunn** [comment]
You only need to specify `GV`. `GV?` and `GV!` are not separate commands, but `GV` command with arguments (`!`, `?`).
