### ISSUE TITLE
Colorcodes when displaying commits diff

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/gv.vim#38]
When I visual-select commits and want to see a diff, I get something like this:
<img width="1414" alt="screen shot 2017-07-04 at 1 00 18 pm" src="https://user-images.githubusercontent.com/10185058/27825621-cf811a6a-60b8-11e7-879b-37d651794855.png">

How can I fix these colorcodes so I get pretty colored diffs?

**Comment by junegunn** [comment]
I don't have the issue, do you have any git configuration that might affect the result of a git command?

**Comment by yevhen-m** [comment]
Thanks, I had 
```
-[color]
-       ui = always
``` 
in my gitconfig.
