### ISSUE TITLE
Commit diff is not triggered on enter

### ISSUE THREAD

**Issue by petobens** [junegunn/gv.vim#49]
Hi @junegunn, I've noticed that pressing enter on a commit message doesn't show the giff anymore. I don't if this has something to with fugitive recent changes or something else:

![jul-21-2018 11-57-48](https://user-images.githubusercontent.com/2583971/43036748-79dbd346-8cdd-11e8-9dd0-581fa1d779fb.gif)

Can you reproduce it? Thanks!

**Comment by mhinz** [comment]
It's broken since https://github.com/tpope/vim-fugitive/commit/0aa3389f5c4b1928c2f5a4c4048d3850c109e753.

**Comment by petobens** [comment]
Thanks!
