### ISSUE TITLE
Commit content displays with folded diff

### ISSUE THREAD

**Issue by hejersbo** [junegunn/gv.vim#5]
When pressing 'o' or <cr> on a commit to display the content of it, the content displays with folded diffs. I think it would be preferable to show the diff unfolded - is there already an option for this that I may have overlooked. Otherwise - great plugin with just the minimal features you always use - easy at hand.

**Comment by junegunn** [comment]
Fugitive is responsible for enabling the fold (`foldenable`). I'm personally not a fan of fold, so I have `set foldlevelstart=99` in my .vimrc which disables fold globally. If you do not want to take such a drastic measure, you could try `set foldlevelstart=1` or `autocmd! FileType git setlocal foldlevel=1` which only applies to git buffers.

**Comment by hejersbo** [comment]
Thanks for the quick response and the suggestions for setting the fold level.
