### ISSUE TITLE
Don't see diff on commit 

### ISSUE THREAD

**Issue by WebWorkDeveloper** [junegunn/gv.vim#51]
![image](https://user-images.githubusercontent.com/8726541/43049008-791b098c-8df9-11e8-9023-5648320f4d8c.png)

Hi, in the file, I use `:GV!` and I will see only list commits that affected the current file. But next, I use `o` and I don't see commit content. I check all my repo, this problem everything.

How I fix it? Thanks.

**Comment by junegunn** [comment]
See #49
