### ISSUE TITLE
Is there any way to change the default diff window width?

### ISSUE THREAD

**Issue by hzchirs** [junegunn/gv.vim#58]
I have to change the diff window with manually.
Is there any way to set the default width for the diff window?

**Comment by jrock2004** [comment]
If you have mouse enabled, you can use it and drag the window wider or shorter

**Comment by mhinz** [comment]
Or maybe `autocmd FileType git vertical resize 80`. It really depends on how you're opening the diff window.

**Comment by hzchirs** [comment]
The `autocmd` way worked! Thanks 😄
