### ISSUE TITLE
Pressing o on commit loses colour syntax

### ISSUE THREAD

**Issue by chris542** [junegunn/gv.vim#61]
I always start my GV with options like so :
`:GV --decorate --all`

, which shows colourful git logs.

But when I open a commit by pressing o or <cr>/enter, I see my commits on my left with colours, but lose colours in my log tree.

Any help?

**Comment by chris542** [comment]
Never mind, apparently I had some code in my .vimrc that messed around with my syntax colours.

**Comment by last5bits** [comment]
@chris542 I'm hitting the same issue. What was it for you that caused the problem?

**Comment by chris542** [comment]
@last5bits Hey man,

I can' remember where I got this code, but I had this chunk in my `.vimrc`

```vimrc
augroup EnableSyntaxHighlighting
    autocmd! BufWinEnter,WinEnter * nested if exists('syntax_on') && ! exists('b:current_syntax') && ! empty(&l:filetype) && index(split(&eventignore, ','), 'Syntax') == -1 | syntax enable | endif
    autocmd! BufRead * if exists('syntax_on') && exists('b:current_syntax') && ! empty(&l:filetype) && index(split(&eventignore, ','), 'Syntax') != -1 | unlet! b:current_syntax | endif
augroup END
```
Which was causing it to lose colour logs when I open a commit on the side.

If you have one, get rid of it! :D

**Comment by last5bits** [comment]
@chris542 Thanks, apparently I had something similar. Works for me now.
