### ISSUE TITLE
Colored tree structure

### ISSUE THREAD

**Issue by languitar** [junegunn/gv.vim#63]
On the command line I use the following command to get a similar view of the history as provided by this plugin:
```
git log --pretty=format:'%C(auto)%h %cd (%G?) %C(green)[%an]%C(auto)%d%Creset %s' --date=short --graph --full-history --all
```
This results in a colored representation of the tree structure:
![image](https://user-images.githubusercontent.com/1336287/62198655-51bd6d80-b382-11e9-968d-2b1177347614.png)

It would be nice if this was also available in GV.

**Comment by mhinz** [comment]
When "using the shell", you have your terminal emulator reading and displaying ANSI escape sequences that are used for coloring.

You don't have something like that in Vim. You can only define regular expressions for certain regions and color them according to a highlight group.

gv uses `--color=never` and colors the raw log output itself.

The closest you can get to what you're asking for is installing [powerman/vim-plugin-AnsiEsc](https://github.com/powerman/vim-plugin-AnsiEsc) first, and then:

```
:enew
:r! git log -30 --oneline --graph --color=always
:AnsiEsc
```

For a long log that can take a while (hence the `-30` limit) and `:AnsiEsc` is not perfect. It doesn't understand all the sequences from my colored log.

Putting it in a nutshell, such a change is complex and will most probably not happen in gv. :)

**Comment by languitar** [comment]
sad to hear as this would be very handy
