### ISSUE TITLE
Vim(return):E700: Unknown function: <SNR>38_LogParse

### ISSUE THREAD

**Issue by cideM** [junegunn/gv.vim#67]
I am on Neovim v0.3.8 using the latest `vim-fugitive` and `gv.vim` on MacOS and I get the error from the title whenever I do `:GV?` in any git controlled file. I added some `echom` to `gv.vim` and the line that fails is `  silent execute a:visual ? "'<,'>" : "" 'Gllog'` in `s:gl`. The `echom` in `fugitive` are never reached, I placed them in 

```
function! fugitive#LogCommand(line1, count, range, bang, mods, args, type) abort
function! fugitive#LogComplete(A, L, P) abort
function! s:CompleteSub(subcommand, A, L, P, ...) abort
```

Running `:Gllog` manually works and all other `:GV` commands work as well.

**Comment by magicalbanana** [comment]
@junegunn any thoughts on this sir?

**Comment by mhinz** [comment]
It's a bug in fugitive and should be fixed soon: https://github.com/tpope/vim-fugitive/pull/1373 (see [this](https://github.com/tpope/vim-fugitive/pull/1370#issue-325378104) for an explanation of the error).

**Comment by mhinz** [comment]
(This issue can be closed.)
