### ISSUE TITLE
not in git repo error ?

### ISSUE THREAD

**Issue by mckellyln** [junegunn/gv.vim#69]
Hi, thank you for gv, it is awesome, I use it almost every day.
Since perhaps the most recent fugitive update (just guessing) however it seems gv no longer works ok.  I always get the error:  not in git repo

This code perhaps no longer determines the git dir correctly ?:
```
function! s:git_dir()
  if empty(get(b:, 'git_dir', ''))
    return fugitive#extract_git_dir(expand('%:p'))
  endif
  return b:git_dir
endfunction
```
I will start to debug.  @tpope fyi.

**Comment by mckellyln** [comment]
Perhaps it is because I often invoke GV from an empty buffer and there was a change in fugitive:
```
@@ -181,6 +181,8 @@ function! FugitiveExtractGitDir(path) abort
   let path = s:Slash(a:path)
   if path =~# '^fugitive:'
     return matchstr(path, '\C^fugitive:\%(//\)\=\zs.\{-\}\ze\%(//\|::\|$\)')
+  elseif empty(path)
+    return ''
   elseif isdirectory(path)
     let path = fnamemodify(path, ':p:s?/$??')
```

**Comment by mckellyln** [comment]
Something like this works, but I'm sure there is a better way:
```
function! s:git_dir()
  if empty(get(b:, 'git_dir', ''))
    let l:gdir = fugitive#extract_git_dir(expand('%:p'))
    if empty(l:gdir)
      let l:gpath = './.git'
      if isdirectory(l:gpath)
        return l:gpath
      endif
    endif
    return l:gdir
  endif
  return b:git_dir
endfunction
```

**Comment by mhinz** [comment]
@mckellyln 

There will be two issues though:

1. It will only work if you're in the root of repo.
1. gv will show `.` instead of the repo dir name in the statusline.

But the general approach is correct. So, maybe...

```vim
function! s:git_dir()
  if !empty(get(b:, 'git_dir', ''))
    return b:git_dir
  endif

  let git_dir = finddir('.git', expand('%').';')
  if !empty(git_dir)
    let b:git_dir = fnamemodify(git_dir, ':p:s?/$??')
    return b:git_dir
  endif

  return ''
endfunction
```

**Comment by mckellyln** [comment]
@mhinz awesome, thanks.  Should you or I create a PR for this ?

**Comment by tpope** [comment]
`FugitiveGitDir()` works in empty buffers now. For all intents and purposes `fugitive#extract_git_dir()` is deprecated.

**Comment by mckellyln** [comment]
ok, thank you @tpope.
So I can just do:
```
function! s:git_dir()
  if !empty(get(b:, 'git_dir', ''))
    return b:git_dir
  endif
  let b:git_dir = FugitiveGitDir()
  return b:git_dir
```

**Comment by tpope** [comment]
`FugitiveGitDir()` handles all of that. You can just do

```
function! s:git_dir() abort
  return FugitiveGitDir()
endfunction
```

**Comment by mckellyln** [comment]
cool

**Comment by mhinz** [comment]
Thanks, tpope.

@mckellyln 

You created the issue, so feel free to create a PR that removes `s:git_dir()` entirely and replaces its single use by `FugitiveGitDir()`. :)

**Comment by mckellyln** [comment]
PR https://github.com/junegunn/gv.vim/pull/70 created.
Thank you everyone.
