### ISSUE TITLE
Add an ability to filter branches

### ISSUE THREAD

**Issue by chris542** [junegunn/gv.vim#79]
Hey Junegunn,

would it be possilbe to add a functionality to have all lists of branches on either left/right and you can select :
all
branch A
branch B 

and toggle them to see the branch you selected only?
This would be so useful in case you have messy branch structure.
Also it would be useful when you have multiple features being developed at the same time.

Cheers!

Chris

**Comment by idbrii** [comment]
Does `GV all`, `GV branch-a`, etc accomplish what you want?

GV also tab-completes.
