### ISSUE TITLE
Show only list of modified files

### ISSUE THREAD

**Issue by CaptainQuirk** [junegunn/gv.vim#8]
Hi,

Would it be possible, when doing <CR> on a item, to somehow refresh the list and show beneath the commit the list of files modified/added/deleted etc, much like a ```git diff --name-status``` would return ?

Doing <CR> on a modified file could open a new split with only the differences for the selected file.

Thanks !

**Comment by junegunn** [comment]
A side-effect of [the recent commit](https://github.com/junegunn/gv.vim/commit/84b61f0af37d710701a99564c08308352a34241c) is that now we can `:GV --name-status`, which displays the affect files as well in the browser window. I know this this is not exactly what you requested, but it's better than nothing.

**Comment by junegunn** [comment]
Wrong issue reference :(

**Comment by CaptainQuirk** [comment]
Hi,

Thanks for the update. Out of curiosity, what would be required to implement this ? You seem to have implemented most of the work by:

- Retrieving modified files for each commit
- Printing them nicely indented

I could give a try if you're interested !

**Comment by junegunn** [comment]
I initially thought you wanted to display the list of files in the right window, but it looks like that was a misunderstanding. Is `:GV --name-status` good enough for you? If it's not, what exactly do you want to add to it? Some kind of folding? I personally don't use folds.

**Comment by CaptainQuirk** [comment]
Hi,

I don't use folding either and I don't intend on using it for now. I know very little about vimscript, so maybe what I would like to see implemented can't be done. I'll try and explain it anyway.

As a user, when I enter the :GV command
I see a list of commits entries
When I  press a certain key on a commit line
The screen is somehow redrawn and the list of  modified/added/deleted files appear beneath the commit line, just like it does when launching :GV with the --name-status argument.

So no folding, just‘© a redraw

**Comment by junegunn** [comment]
That's possible. Though I'm not sure if I want to provide it as a builtin feature. It's kind of tricky to get it right when it's possible for a user to pass any `git log` arguments to `:GV`. Anyway, with the following code in your vimrc, you can do it with `+` key.

```vim
function! s:gv_expand()
  let line = getline('.')
  GV --name-status
  call search('\V'.line, 'c')
  normal! zz
endfunction

autocmd! FileType GV nnoremap <buffer> <silent> + :call <sid>gv_expand()<cr>
```

This opens another GV tab with `--name-status` so you can easily go back to the previous tab by closing it with `q`. If you don't like having an extra tab. Add `close` before `GV --name-status`.
