### ISSUE TITLE
Add an ability to revert and reset

### ISSUE THREAD

**Issue by benwtks** [junegunn/gv.vim#80]
It would be great to have the option to revert commits and reset to different points via the log

**Comment by justinmk** [comment]
see https://github.com/junegunn/gv.vim/pull/74 . Rather out of scope for gv.vim IMO. 

You can revert a commit by putting cursor on the git commit id, then:

    :G revert <c-r><c-w>

**Comment by benwtks** [comment]
Ah okay no worries, yeah that works great thanks

I'll add it to my vimrc haha
