### ISSUE TITLE
New tab position

### ISSUE THREAD

**Issue by ipod825** [junegunn/gv.vim#82]
https://github.com/junegunn/gv.vim/blob/61d877d23caaad9009d672f90fe2ab576ab93d2d/plugin/gv.vim#L47

Is there any reason why the new tab is put in the left of the current tab? This makes quitting gv bring user to another tab rather than the original tab starting gv.

**Comment by somini** [comment]
It does? I think it's the opposite, when you quit the `gv` tab you return to the previously used tab.
