### ISSUE TITLE
gh command not found

### ISSUE THREAD

**Issue by GopherJ** [junegunn/gv.vim#87]
![image](https://user-images.githubusercontent.com/33961674/102317796-7e265980-3f78-11eb-814c-c16197c249ba.png)
Hi, I got this while using `blamePR`, I checked my zshrc there isn't anything called gh, any idea on it?

**Comment by junegunn** [comment]
Don't know what `blamePR` is. Wrong repository?

**Comment by GopherJ** [comment]
@junegunn emmm...  sorry it's for fzf-preview
