### ISSUE TITLE
Filter list items

### ISSUE THREAD

**Issue by CaptainQuirk** [junegunn/gv.vim#9]
Hi,

Would it be possible to implement some sort of filtering:

- by author
- by date
- by branch
- by any string (git log -S option)

Thanks !

**Comment by junegunn** [comment]
Yeah, it can be useful if we allow custom arguments to the `git log` command, e.g. `:GV devel`. I'll think about the options.

**Comment by junegunn** [comment]
Now you can do things like:

- Author
    - `:GV --author Linus`
- Date
    - `:GV --until 2011-01-01`
- Search
    - `:GV -S GPL`
- Branch
    - `:GV devel`

Note that I had to make sure that arbitrary formatting options are ignored not to break the current implementation.
