### ISSUE TITLE
:Gbrowse is deprecated in favor of :GBrowse, fix it to GBrowse?

### ISSUE THREAD

**Issue by thepenguinthatwants** [junegunn/gv.vim#91]
Hi,
Your plugins are always super nice, but seems like fugitive has deprecated Gbrowse and changed it to GBrowse.
Can you fix it to GBrowse?

**Comment by junegunn** [comment]
Thanks for the heads up. Looks like a year has passed since `GBrowse` was added to Fugitive, so I think it's safe to use it now.

https://github.com/tpope/vim-fugitive/commit/9bbbb65888293f6d6a4da55bc8b0d8907ba779d4

Are you willing to open a pull request?
